name: Zefr Engineering Blog
title: Zefr | Engineering Blog
description: Technical, cultural, and philosophical musings by Zefr engineering
tags:
  - python
  - react
  - frontend
  - backend
show_hero: true
# menu:
#   - title: Home
#     url: /
#   - title: About
#     url: /about
#   - title: Contact
#     url: /contact
#   - title: Feed
#     url: /feed.xml
email: javier.armendariz@zefr.com
disqus_username:
